(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const state = { image: null, fileName: '', width: 0, height: 0, x: 74, y: 50, dragging: false, cancelled: false };
  const els = {
    imageInput: $('imageInput'), dropZone: $('dropZone'), replaceImage: $('replaceImage'), imageInfo: $('imageInfo'), fileName: $('fileName'), imageDimensions: $('imageDimensions'),
    canvas: $('previewCanvas'), stage: $('canvasStage'), emptyState: $('emptyState'), dragHint: $('dragHint'), previewState: $('previewState'), previewNumber: $('previewNumber'),
    start: $('startNumber'), end: $('endNumber'), pad: $('padWidth'), template: $('fileTemplate'), rangeHelper: $('rangeHelper'), font: $('fontFamily'), fontSize: $('fontSize'),
    color: $('textColor'), bold: $('boldText'), fontWeight: $('fontWeight'), fontStyle: $('fontStyle'), letterSpacing: $('letterSpacing'), scaleX: $('scaleX'), rotation: $('rotation'), outline: $('outlineText'), outlineFields: $('outlineFields'), outlineColor: $('outlineColor'), outlineWidth: $('outlineWidth'), shadow: $('shadowText'), shadowFields: $('shadowFields'), shadowOffsetFields: $('shadowOffsetFields'), shadowColor: $('shadowColor'), shadowBlur: $('shadowBlur'), shadowOffsetX: $('shadowOffsetX'), shadowOffsetY: $('shadowOffsetY'),
    opacity: $('opacity'), opacityValue: $('opacityValue'), x: $('positionX'), y: $('positionY'), coord: $('coordReadout'), output: $('outputReadout'),
    download: $('downloadCurrent'), generate: $('generateZip'), summary: $('exportSummary'), progressWrap: $('progressWrap'), progressLabel: $('progressLabel'), progressBar: $('progressBar'), cancel: $('cancelBatch')
  };
  const settings = () => ({ font: els.font.value, size: Number(els.fontSize.value) / 100, color: els.color.value, weight: els.fontWeight.value, style: els.fontStyle.value, bold: els.bold.checked, letterSpacing: Number(els.letterSpacing.value) / 100, scaleX: Number(els.scaleX.value) / 100, rotation: Number(els.rotation.value), outline: els.outline.checked, outlineColor: els.outlineColor.value, outlineWidth: Number(els.outlineWidth.value), shadow: els.shadow.checked, shadowColor: els.shadowColor.value, shadowBlur: Number(els.shadowBlur.value), shadowOffsetX: Number(els.shadowOffsetX.value), shadowOffsetY: Number(els.shadowOffsetY.value), opacity: Number(els.opacity.value) / 100 });
  const range = () => { let start = Math.max(0, Math.floor(Number(els.start.value) || 0)); let end = Math.max(start, Math.floor(Number(els.end.value) || start)); const pad = Number(els.pad.value); const count = Math.min(end - start + 1, 500); return { start, end: start + count - 1, pad, count }; };
  const formatted = (num) => { const r = range(); return String(num).padStart(r.pad, '0'); };
  const currentNumber = () => Number(els.previewNumber.value || range().start);
  const fileBase = (num) => { const safe = (els.template.value.trim() || 'image-{number}').replaceAll('{number}', formatted(num)).replace(/[\\/:*?"<>|]/g, '-'); return `${safe}.png`; };
  const updateRange = () => {
    const r = range(); els.rangeHelper.textContent = `共生成 ${r.count} 张 · 示例：${fileBase(r.start)}`; els.summary.textContent = state.image ? `${r.count} 张 PNG · ${state.width} × ${state.height}px · 文件名示例 ${fileBase(r.start)}` : '上传背景图后即可开始。';
    const old = currentNumber(); els.previewNumber.innerHTML = ''; for (let n = r.start; n <= r.end; n += 1) { const opt = document.createElement('option'); opt.value = n; opt.textContent = formatted(n); els.previewNumber.appendChild(opt); } els.previewNumber.value = Math.min(Math.max(old, r.start), r.end); draw();
  };
  const setupCanvas = () => { const maxW = els.stage.clientWidth - 70; const maxH = els.stage.clientHeight - 70; const scale = Math.min(maxW / state.width, maxH / state.height, 1); els.canvas.width = Math.max(1, Math.round(state.width * scale)); els.canvas.height = Math.max(1, Math.round(state.height * scale)); draw(); };
  const draw = (targetCanvas = els.canvas, number = currentNumber()) => {
    if (!state.image) return; const ctx = targetCanvas.getContext('2d'); const scale = targetCanvas.width / state.width; ctx.clearRect(0, 0, targetCanvas.width, targetCanvas.height); ctx.drawImage(state.image, 0, 0, targetCanvas.width, targetCanvas.height);
    const s = settings(); const fontPx = Math.max(8, state.height * s.size * scale); const text = formatted(number); const x = targetCanvas.width * state.x / 100; const y = targetCanvas.height * state.y / 100; const letterSpacing = fontPx * s.letterSpacing; ctx.save(); ctx.globalAlpha = s.opacity; ctx.translate(x, y); ctx.rotate(s.rotation * Math.PI / 180); ctx.scale(s.scaleX, 1); ctx.font = `${s.style} ${s.weight === '700' && s.bold ? 800 : s.weight} ${fontPx}px ${s.font}`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.shadowColor = s.shadow ? s.shadowColor : 'transparent'; ctx.shadowBlur = s.shadow ? s.shadowBlur * scale : 0; ctx.shadowOffsetX = s.shadow ? s.shadowOffsetX * scale : 0; ctx.shadowOffsetY = s.shadow ? s.shadowOffsetY * scale : 0; const drawText = (method) => { if (letterSpacing === 0 || text.length < 2) { ctx[method](text, 0, 0); return; } const widths = [...text].map(char => ctx.measureText(char).width); const total = widths.reduce((sum, width) => sum + width, 0) + letterSpacing * (widths.length - 1); let cursor = -total / 2; [...text].forEach((char, index) => { ctx[method](char, cursor + widths[index] / 2, 0); cursor += widths[index] + letterSpacing; }); }; if (s.outline) { ctx.lineWidth = s.outlineWidth * scale; ctx.strokeStyle = s.outlineColor; drawText('strokeText'); } ctx.fillStyle = s.color; drawText('fillText'); ctx.restore();
    els.coord.textContent = `${state.x.toFixed(1)}% / ${state.y.toFixed(1)}%`; els.output.textContent = `${state.width} × ${state.height}px`; els.previewState.textContent = `${formatted(number)} · 拖动序号调整位置`;
  };
  const loadFile = (file) => { if (!file || !file.type.startsWith('image/')) return; const url = URL.createObjectURL(file); const img = new Image(); img.onload = () => { state.image = img; state.fileName = file.name; state.width = img.naturalWidth; state.height = img.naturalHeight; els.fileName.textContent = file.name; els.imageDimensions.textContent = `${state.width} × ${state.height}px`; els.imageInfo.hidden = false; els.emptyState.hidden = true; els.canvas.style.display = 'block'; els.dragHint.hidden = false; els.previewNumber.disabled = false; els.download.disabled = false; els.generate.disabled = false; setupCanvas(); updateRange(); URL.revokeObjectURL(url); }; img.src = url; };
  const updatePosition = (clientX, clientY) => { if (!state.image) return; const rect = els.canvas.getBoundingClientRect(); state.x = Math.max(0, Math.min(100, (clientX - rect.left) / rect.width * 100)); state.y = Math.max(0, Math.min(100, (clientY - rect.top) / rect.height * 100)); els.x.value = state.x.toFixed(1); els.y.value = state.y.toFixed(1); draw(); };
  const downloadBlob = (blob, name) => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const renderExport = (number) => { const canvas = document.createElement('canvas'); canvas.width = state.width; canvas.height = state.height; draw(canvas, number); return new Promise(resolve => canvas.toBlob(resolve, 'image/png')); };
  const showProgress = (show) => { els.progressWrap.hidden = !show; if (!show) { els.progressBar.style.width = '0%'; } };
  els.imageInput.addEventListener('change', (e) => loadFile(e.target.files[0])); els.replaceImage.addEventListener('click', () => els.imageInput.click());
  ['dragenter', 'dragover'].forEach(type => els.dropZone.addEventListener(type, e => { e.preventDefault(); els.dropZone.classList.add('is-over'); })); ['dragleave', 'drop'].forEach(type => els.dropZone.addEventListener(type, e => { e.preventDefault(); els.dropZone.classList.remove('is-over'); })); els.dropZone.addEventListener('drop', e => loadFile(e.dataTransfer.files[0]));
  els.canvas.addEventListener('pointerdown', e => { state.dragging = true; els.canvas.setPointerCapture(e.pointerId); updatePosition(e.clientX, e.clientY); }); els.canvas.addEventListener('pointermove', e => { if (state.dragging) updatePosition(e.clientX, e.clientY); }); ['pointerup', 'pointercancel'].forEach(type => els.canvas.addEventListener(type, () => { state.dragging = false; }));
  [els.start, els.end, els.pad, els.template].forEach(el => el.addEventListener('input', updateRange)); els.previewNumber.addEventListener('change', draw);
  [els.font, els.fontSize, els.color, els.bold, els.fontWeight, els.fontStyle, els.letterSpacing, els.scaleX, els.rotation, els.outline, els.outlineColor, els.outlineWidth, els.shadow, els.shadowColor, els.shadowBlur, els.shadowOffsetX, els.shadowOffsetY].forEach(el => el.addEventListener('input', () => { els.outlineFields.hidden = !els.outline.checked; els.shadowFields.hidden = !els.shadow.checked; els.shadowOffsetFields.hidden = !els.shadow.checked; draw(); })); els.opacity.addEventListener('input', () => { els.opacityValue.textContent = `${els.opacity.value}%`; draw(); });
  [els.x, els.y].forEach((el, i) => el.addEventListener('input', () => { state[i ? 'y' : 'x'] = Math.max(0, Math.min(100, Number(el.value) || 0)); draw(); })); document.querySelectorAll('[data-align]').forEach(btn => btn.addEventListener('click', () => { if (btn.dataset.align === 'left') state.x = 15; if (btn.dataset.align === 'center') state.x = 50; if (btn.dataset.align === 'right') state.x = 85; els.x.value = state.x; draw(); }));
  els.download.addEventListener('click', async () => { if (!state.image) return; els.download.disabled = true; els.download.textContent = '准备中…'; downloadBlob(await renderExport(currentNumber()), fileBase(currentNumber())); els.download.disabled = false; els.download.textContent = '下载当前 PNG'; });
  els.cancel.addEventListener('click', () => { state.cancelled = true; });
  els.generate.addEventListener('click', async () => { if (!state.image || !window.JSZip) { alert('批量压缩功能需要网络加载 ZIP 组件，请检查网络后重试。'); return; } const r = range(); state.cancelled = false; showProgress(true); els.generate.disabled = true; const zip = new JSZip(); for (let i = 0; i < r.count; i += 1) { if (state.cancelled) break; const num = r.start + i; const blob = await renderExport(num); zip.file(fileBase(num), blob); const percent = Math.round((i + 1) / r.count * 100); els.progressBar.style.width = `${percent}%`; els.progressLabel.textContent = `正在生成 ${i + 1} / ${r.count} · ${formatted(num)}`; await new Promise(requestAnimationFrame); } if (!state.cancelled) { els.progressLabel.textContent = '正在打包…'; downloadBlob(await zip.generateAsync({ type: 'blob' }), `${(els.template.value.trim() || 'image').replace('{number}', 'set')}.zip`); els.progressLabel.textContent = `完成 · 已生成 ${r.count} 张 PNG`; } else { els.progressLabel.textContent = '已取消'; } els.generate.disabled = false; setTimeout(() => showProgress(false), 1400); });
  window.addEventListener('resize', () => { if (state.image) setupCanvas(); }); updateRange();
})();
